//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsusStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class databarang
    {
        public int kodebarang { get; set; }
        public string Namabarang { get; set; }
        public string Hargabarang { get; set; }
        public string Stokbarang { get; set; }
    }
}
